/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

/* Declarar función externa */
void configureTimer3(void);



/* CREACION DE VARIABLES PARA EJERCICIO DE CLASE 14 DE MAYO

TAREAS:

1. Crear 3 variables de 8 bits de 16 y de 32


*/

uint8_t variable8bit = 0;
uint16_t variable16bit = 0;
uint32_t variable32bit = 0;

uint16_t variable16_16bit_dec = 0;
uint16_t variable16_16bit_bin = 0;
uint16_t variable16_16bit_hex = 0;
uint8_t overflow_demo = 0;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	variable8bit = 123;
	variable16bit=4986;
	variable32bit=12345678;

	variable16_16bit_dec = 32;
	variable16_16bit_hex = 0x20;
	variable16_16bit_bin = 0b100000;





	variable16_16bit_bin = variable16_16bit_bin << 3;
	variable16_16bit_bin = variable16_16bit_bin >> 3;


	/*exponiendo el caso deun overflow */

	variable8bit = 255;
	variable16bit = 255;
	variable32bit = 255;

	/*Incremento del valor de la variable variable8bit en 1 y lo cargo en la variable
	 * overflow demo
	 */

	overflow_demo = variable8bit + 1;
	overflow_demo = overflow_demo + 1;

	/* Cargamos un valor mas grande del que puede soportar
	 * LO QUE ESTA PASANDO ES QUE INTENTA METER UNA COSA GRANDE EN ALGO QUE NO CABE.
	 * Entonces lo que hace es que corta lo que no cabe como si estuviera metiendo una forma en un cuadro de un tamaño
	 * determinado, y entonces se corta lo que es mas grande que el bloque y deja solo lo del cuadro original.
	 */
	overflow_demo = 735;

	/* EL aprendizaje de aqui es que no podemos darle un numero a una variable que
	 * no es capaz de contenerla. Entonces con este overflow se ilustran estos casos.
	 */


	overflow_demo = 0;
	for (uint16_t counter = 0; counter < 735; counter++){

		overflow_demo++;
	}




	/* Loop forever */
	while(1){



	}

}
